os:
  - linux
#  - osx
language: java
dist: xenial
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.cache
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/core/target
    - $TRAVIS_BUILD_DIR/launcher/target

install: true

jobs:
  include:
    # Do the actual build (and test reporting)
    - stage: package (maven)
      script: mvn --settings ./ci/.travis-settings.xml -B         clean package -P distribute

    - stage: report tests to sonarqube (maven)
      if: branch =~ ^release\/.*$
      script: mvn --settings ./ci/.travis-settings.xml -B -f core sonar:sonar

    # Distribute binairies
    - stage: distribute
      if: branch =~ ^release\/.*$
      script: mvn --settings ./ci/.travis-settings.xml -B -f core jar:jar deploy:deploy

    - stage: distribute
      if: branch =~ ^release\/.*$
      script: mvn --settings ./ci/.travis-settings.xml -B -f launcher jar:jar deploy:deploy

    - stage: distribute
      if: branch =~ ^release\/.*$
      services:
        - docker
      script: (cd ./launcher/target/docker/ && bash build.sh)

    - stage: distribute
      script: true
      deploy:
        provider: releases
        skip_cleanup: true
        token: $GITHUB_OAUTH
        draft: true
        file_glob: true
        file: launcher/target/dist/*
        on:
          tags: true
