os:
  - linux
  - osx
sudo: false
language: java
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"

deploy:
  provider: script
  script:
    - mvn deploy -Pdistribute --settings .travis-settings.xml -DskipTests=true -B
    # - ./target/image/build.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.*$ && $TRAVIS_OS_NAME == "linux"