os:
  - linux
  - osx
sudo: false
language: java
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"

deploy:
  provider: script
  script: 'bash deploy.sh'
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.*$ && $TRAVIS_OS_NAME == "linux"