os:
  - linux
#  - osx
language: java
dist: xenial
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.cache
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/core/target
    - $TRAVIS_BUILD_DIR/launcher/target

install: true

jobs:
  include:
    # Do the actual build (and test reporting)
    - stage: package (maven)
      script: mvn -B clean package -Pdistribute

    - stage: report tests (sonarqube)
      if: branch =~ ^release\/.*$
      script: mvn -B -DskipTests=true -f core org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=inv
      addons:
        sonarcloud:
          organization: "peasoupio"
          token:
            secure: "XUXzae/R2J14wKvO2VbRTU5pT7CvHuXpKv/qyZakBvkdYcuRYdDspsVPObJ+Heogh+gAi2s2M0Yhn+ebqY/ouKBhwG+ekNy/0J3o32lCHzSKLRxb/l3lgGYr51RoEBuaddYZ83+xUxGu8mEv9HdzPoNTtg7h3WEdmslklYerI1/oxIB0RWOy+8npB9j2rS7fPRx13EZUnyabVNXox7359rIoepVOqLrrOzYPK/5gtSiylaj8jMD1fvY6CdoZQQfM4MxSCLVVZnJiv3ojrwGczIaFLGpe5Jh85SE10Lzk/VGB43upJOC2xcrZ6tqHMAsmZ/6anSykw8SCK9qMJKNhEC0P43rmJfZBO7jmMz/4UCrzUwZUz7K7gdKCFjomdEnx1ozSzMMBaOhKdvvbe2p2ArjQQipErfhVW585yRpE3TemhUbu+3vKqkc46A3LRQjlr3dXe3JMqdNf2VudN5IeWgoxC5xVLjAd5VmAMaEkdm+mpnyXVE5v1hhSiEqyePDQXIiMLAUJbWunEjGNMgb26N23dUUje+m7rqEwk2q7+Yj/rlptsnQBkQ4Dh6iTw0/xYdBLzW5ebujOfhL3Zg94+pIJN/OkcJXYrbJ9mA6voS9ipwSu9qX91i1BOixLYAxMjJfPDLH3+WnF099uPuKTufs4RHR5qirGsYZLBawL+wI="

    # Distribute binairies
    - stage: distribute
      if: branch =~ ^release\/.*$
      script: mvn -B -DskipTests=true deploy --settings ./ci/.travis-settings.xml

    - stage: distribute
      if: branch =~ ^release\/.*$
      services:
        - docker
      script: (cd ./launcher/target/docker/ && bash build.sh)

    - stage: distribute
      script: true
      deploy:
        provider: releases
        skip_cleanup: true
        token: $GITHUB_OAUTH
        draft: true
        file_glob: true
        file: launcher/target/dist/*
        on:
          tags: true
