os:
  - linux
  - osx
sudo: false
language: java
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"

env:
  global:
    - secure: encrypted env-variable OSSRH_USERNAME
    - secure: encrypted env-variable OSSRH_PASSWORD

deploy:
  provider: script
  script: "mvn deploy --settings .travis-settings.xml -DskipTests=true -B"
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.*$ && $TRAVIS_OS_NAME == "linux"