#!/bin/sh

# Get parent directory of this script
BASEDIR=$(dirname $(dirname "$0"))

# Get lib directory
LIBDIR=$BASEDIR/../lib

# Get INV jar
INVJAR=${project.artifactId}-${project.version}.jar

# Call INV jar with parameters
java -jar $LIBDIR/$INVJAR $@