#!/bin/sh

# Get parent directory of this script
BASEDIR=$(dirname $(dirname "$0"))

# Get lib directory
LIBDIR=$BASEDIR/../lib

# Get INV jar
INVJAR=${project.artifactId}-${project.version}.jar

# Set Java properties
JAVAPROPS=-Djava.system.class.loader=groovy.lang.GroovyClassLoader

# Call INV jar with parameters
java $JAVAPROPS -jar $LIBDIR/$INVJAR $@